# Generated by Django 2.0 on 2019-05-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20190519_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='title',
        ),
        migrations.AddField(
            model_name='step',
            name='linker',
            field=models.CharField(max_length=255, null=True, verbose_name='リンク名'),
        ),
        migrations.AddField(
            model_name='step',
            name='number',
            field=models.IntegerField(null=True, verbose_name='ステップ番号'),
        ),
    ]
