# Generated by Django 2.0 on 2019-05-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20190519_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='loc',
            field=models.IntegerField(default=0, unique=True, verbose_name='位置番号'),
        ),
    ]
