# Generated by Django 2.0 on 2019-05-19 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20190519_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='initial_step',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='out_tasks', to='todo.Step', verbose_name='始点'),
        ),
        migrations.AlterField(
            model_name='task',
            name='terminal_step',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='in_tasks', to='todo.Step', verbose_name='終点'),
        ),
    ]
