# Generated by Django 2.0 on 2019-05-20 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_auto_20190520_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 21, 1, 39, 1, 543095), verbose_name='納期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 21, 0, 39, 1, 542912), null=True, verbose_name='着手日時'),
        ),
    ]
