# Generated by Django 2.0 on 2019-05-20 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_auto_20190521_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 21, 1, 43, 25, 212700), verbose_name='納期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 21, 0, 43, 25, 212519), null=True, verbose_name='着手日時'),
        ),
    ]
