# Generated by Django 2.0 on 2019-05-18 15:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprig', '0002_auto_20190516_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='ステップ名')),
            ],
            options={
                'db_table': 'steps',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='タスク名')),
                ('start', models.DateTimeField(default=models.DateTimeField(auto_now_add=True), verbose_name='着手日時')),
                ('expected_time', models.DateTimeField(default=datetime.timedelta(0), verbose_name='予想時間')),
                ('actual_time', models.DateTimeField(default=datetime.timedelta(0), verbose_name='実績時間')),
                ('deadline', models.DateTimeField(default=models.DateTimeField(default=models.DateTimeField(auto_now_add=True), verbose_name='着手日時'), verbose_name='納期')),
                ('client', models.IntegerField(default=0, verbose_name='依頼者')),
                ('is_done', models.BooleanField(default=False, verbose_name='完了')),
                ('note', models.TextField(null=True, verbose_name='備考')),
                ('initial_step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='initial_step', to='sprig.Step', verbose_name='始点')),
                ('terminal_step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='terminal_step', to='sprig.Step', verbose_name='終点')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
