# Generated by Django 2.0 on 2019-05-18 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprig', '0003_auto_20190519_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='actual_time',
            field=models.DateTimeField(default=datetime.timedelta(0, 3600), verbose_name='実績時間'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(verbose_name='納期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='expected_time',
            field=models.DateTimeField(default=datetime.timedelta(0, 3600), verbose_name='予想時間'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(null=True, verbose_name='着手日時'),
        ),
    ]
