# Generated by Django 2.0 on 2019-05-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprig', '0006_auto_20190519_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='number',
        ),
        migrations.AddField(
            model_name='step',
            name='loc',
            field=models.IntegerField(null=True, verbose_name='位置番号'),
        ),
    ]
