# Generated by Django 2.0 on 2019-05-20 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprig', '0012_auto_20190520_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='actual_time',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='実績時間'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 20, 21, 16, 42, 954498), verbose_name='納期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='expected_time',
            field=models.DurationField(default=datetime.timedelta(0, 3600), verbose_name='予想時間'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 20, 20, 16, 42, 954318), null=True, verbose_name='着手日時'),
        ),
    ]
