# Generated by Django 2.0 on 2019-05-21 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprig', '0015_auto_20190521_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 21, 15, 1, 55, 185419), verbose_name='納期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 21, 14, 1, 55, 185230), null=True, verbose_name='着手日時'),
        ),
    ]
