# Generated by Django 2.0 on 2019-06-05 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprig', '0016_auto_20190521_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 5, 13, 0, 41, 63653), verbose_name='納期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 5, 12, 0, 41, 63467), null=True, verbose_name='着手日時'),
        ),
    ]
