# Generated by Django 2.0 on 2019-06-07 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprig', '0017_auto_20190605_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 12, 44, 47, 438170), verbose_name='納期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 11, 44, 47, 437981), null=True, verbose_name='着手日時'),
        ),
    ]
