# Generated by Django 2.0 on 2019-06-22 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprig', '0022_auto_20190619_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 22, 18, 37, 3, 46029), verbose_name='納期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 22, 17, 37, 3, 45959), null=True, verbose_name='着手日時'),
        ),
    ]
